### ISSUE TITLE
Clean dependency updates

### ISSUE THREAD

**Issue by ylyangtw** [ncsa/datawolf#27]
There are several dependency updates from dependabot. Make changes accordingly and test them.
https://github.com/ncsa/datawolf/pull/13
https://github.com/ncsa/datawolf/pull/7
https://github.com/ncsa/datawolf/pull/6
https://github.com/ncsa/datawolf/pull/5

**Comment by ylyangtw** [comment]
@navarroc I have tested those 4 dependency updates, all work well together (tested created tool, executed the tool, checked the output). But I don't have the permission to review/assign/merge issues. Could you grant me the access?

**Comment by navarroc** [comment]
How did you test the hsql one? For that you would need to make hsql the DB instead of postgres by either building locally with maven, updating docker-compose to remove postgres so falls back to hsql or just running the pure docker image of datawolf. Did you do one of those?

On a separate note, let me add you as reviewer to the PR's and if you tested them, approve them and I can merge them.

**Comment by navarroc** [comment]
I found hsqldb is not compatible with java 8 by default (running mvn clean install fails because it runs the unit tess). By default, maven will download the java 11 version so I think we need to make our own PR for hsqldb - see this post here: https://stackoverflow.com/questions/74261785/how-to-get-hsqldb-2-7-1-jdk8-jar-from-maven-central-repository

Wherever we specify hsqldb, we need a the parameter mentioned in the slack post.

**Comment by ylyangtw** [comment]
> How did you test the hsql one? For that you would need to make hsql the DB instead of postgres by either building locally with maven, updating docker-compose to remove postgres so falls back to hsql or just running the pure docker image of datawolf. Did you do one of those?
> 
> On a separate note, let me add you as reviewer to the PR's and if you tested them, approve them and I can merge them.

Oh no sorry, I only tested the functionalities without enabling hsql. I can test those too. Just curious -- when do we need to enable hsql?
